// Run with PREVIOUS_BUILD_PATH pointing to the backed-up Build 23 snapshot.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const next=path.join(__dirname,'..'),previous=process.env.PREVIOUS_BUILD_PATH;if(!previous)throw new Error('PREVIOUS_BUILD_PATH must point to Build 23');let root=previous;
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://localhost').pathname,file=path.join(root,pathname==='/'?'index.html':pathname);if(!fs.existsSync(file)){res.writeHead(404);return res.end()}res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.html')?'text/html':file.endsWith('.webmanifest')?'application/manifest+json':'image/png');res.end(fs.readFileSync(file))});
const stored=()=>new Promise(resolve=>{const q=indexedDB.open('pandas-tripmaster-gps',2);q.onsuccess=()=>{const t=q.result.transaction(['sessions','points']),s=t.objectStore('sessions').getAll(),p=t.objectStore('points').getAll();t.oncomplete=()=>resolve({ledger:localStorage.tripmasterLedgerV2,regularity:localStorage.tripmasterRegularityV1,sessions:s.result,points:p.result})}});
(async()=>{await new Promise(r=>server.listen(8771,'127.0.0.1',r));const b=await chromium.launch({headless:true});try{
 const ctx=await b.newContext(),p=await ctx.newPage();await p.addInitScript(()=>Object.defineProperty(navigator,'geolocation',{value:{watchPosition(cb){window.testGps=cb;return 1},clearWatch(){}}}));p.on('dialog',d=>d.accept());
 await p.goto('http://127.0.0.1:8771/?app=23');await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForTimeout(500);
 await p.click('[data-adjust="100"]');await p.click('#openRegularity');await p.evaluate(()=>testGps({timestamp:Date.now(),coords:{latitude:48.2,longitude:16.4,accuracy:5,speed:0}}));await p.click('#regStart');await p.click('#regAction');
 await p.evaluate(()=>new Promise(resolve=>{const q=indexedDB.open('pandas-tripmaster-gps',2);q.onsuccess=()=>{const t=q.result.transaction(['sessions','points'],'readwrite');t.objectStore('sessions').put({id:'existing',stageNumber:9,startTime:1000,endTime:2000,distanceM:120});t.objectStore('points').add({sessionId:'existing',number:1,latitude:48.2,longitude:16.4,accepted:true,timestamp:1000});t.oncomplete=resolve}}));
 const before=await p.evaluate(stored);await p.evaluate(async()=>{const c=await caches.open('unrelated-app');await c.put('/unrelated-marker',new Response('keep'))});
 root=next;await p.reload();await p.waitForFunction(async()=>(await caches.keys()).includes('tripmaster-v24-github'));await p.waitForTimeout(600);assert.deepEqual(await p.evaluate(stored),before,'Build 23 counters, sessions, raw points and GLP recovery survive Build 24');
 assert.equal(await p.textContent('#startStop'),'TRIPMASTER START');assert.equal(await p.getAttribute('#totalKm','data-value'),'0,10');assert(await p.evaluate(async()=>await caches.has('unrelated-app')),'unrelated caches preserved');
 await ctx.setOffline(true);await p.reload();assert.equal(await p.title(),'PANDAs Tripmaster');assert.equal(await p.evaluate(()=>typeof RouteMap.zoom),'function');assert.deepEqual(await p.evaluate(stored),before,'offline reload keeps records');
 console.log('PASS: real service-worker Build 23 → 24 upgrade and offline reload preserve counters, raw GPS, sessions and existing single GLP recovery; unrelated cache preserved.');
 }finally{await b.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
